Portal/Controllers/PermitInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Portal.Models.DB;
using Portal.Models.ViewModel;
using System.Web.Services;
using System.IO;

namespace Portal.Controllers
{
    public class PermitInfoController : Controller
    {
        private CityworksEntities db = new CityworksEntities();
       
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult GetPermitInfo(string permitNum)
        {
            var tab = (from c in db.CA_OBJECT_VW
                      where c.CASE_NUMBER.Contains(permitNum)
                      select c).ToList();
            return PartialView("_PermitInfo", tab);
        }

        public ActionResult GetPermitLocation(string permitNum)
        {
            var tab = (from a in db.CA_ADDRESS_VW
                       where a.CASE_NUMBER.Contains(permitNum)
                       select a).ToList();
            return PartialView("_PermitLocation", tab);
        }

        public ActionResult GetPermitPeople(string permitNum)
        {
            var tab = (from p in db.CA_PEOPLE_VW
                       where p.CASE_NUMBER.Contains(permitNum)
                       select p).ToList();
            return PartialView("_PermitPeople", tab);
        }

        public ActionResult GetPermitTasks(string permitNum)
        {
            var tab = (from t in db.CA_TASK_VW
                       where t.CASE_NUMBER.Contains(permitNum)
                       orderby t.TASK_ID
                       select t).ToList();
            return PartialView("_PermitTasks", tab);
        }

        public ActionResult GetPermitInspections(string permitNum)
        {
            var tab = (from i in db.CA_INSPECTION_REQ_VW
                       where i.CASE_NUMBER.Contains(permitNum)
                       select i).ToList();
            return PartialView("_PermitInspections", tab);
        }

        public ActionResult GetPermitFees(string permitNum)
        {
            var tab = (from f in db.CA_FEES_VW
                       where f.CASE_NUMBER.Contains(permitNum)
                       select f).ToList();
            return PartialView("_PermitFees", tab);
        }

        public ActionResult GetPermitPayments(string permitNum)
        {
            var tab = (from p in db.CA_PAYMENT_VW
                       where p.CASE_NUMBER.Contains(permitNum)
                       select p).ToList();
            return PartialView("_PermitPayments", tab);
        }

        
    }
}

Portal/Controllers/SearchByLocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Portal.Models.DB;

namespace Portal.Controllers
{
    public class SearchByLocationController : Controller
    {
        private CityworksEntities db = new CityworksEntities();
        // GET: SearchByLocation
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SearchLocation()
        {
            return PartialView("_SearchLocation");
        }

        [HttpPost]
        public PartialViewResult SearchLocation(string location)
        {
            var tab = (from p in db.CA_OBJECT_VW
                       where p.LOCATION.Contains(location)
                       select p).ToList();
            return PartialView("_SearchLocationResults", tab);
        }
    }
}

Portal/Views/SearchByLocation/Index.cshtml
@{
    ViewBag.Title = "Search Permits by Location";
    ViewBag.Icon = @"<i class=""fa fa-search""></i>";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*@Scripts.Render("http://js.arcgis.com/3.14/")
@Scripts.Render("~/scripts/MapHelper.js")*@
@*<link rel="stylesheet" href="http://js.arcgis.com/3.14/esri/css/esri.css" />*@

<div id="search-form">
    @Html.Action("SearchLocation", "SearchByLocation")
</div>

@*<div class="form-group">
    <div class="row">
        <div class="col-sm-12">
            <div class="claro" id="mapDiv"></div>
        </div>
    </div>
</div>*@

<div id="search-results"></div>

<script>
   
</script>

Portal/Views/SearchByLocation/_SearchLocation.cshtml
@using (Html.BeginForm("SearchLocation", "SearchByLocation", FormMethod.Post, new { @class = "col-sm-12" }))
{
    @*<div class="form-group">
        <div class="row">
            <div class="col-sm-6">
                @Html.TextBox("location", null, new { @class = "form-control", @placeholder = "Enter location", required = "required", text = "" })
            </div>
        </div>
    </div>*@

     <div class="row">
        <div class="form-group label-floating">
            <div class="col-sm-6">
                <label for="locationName" class="control-label">Enter Location</label>
                @Html.TextBox("location", null, new { @class = "form-control", required = "required" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <button type="submit" class="btn btn-raised btn-primary">Search</button>
        </div>
    </div>
    @Html.Hidden("address", null, new { @class = "selected-address-two" });
}

Portal/Views/SearchByLocation/_SearchLocationResults.cshtml
@model IEnumerable<Portal.Models.DB.CA_OBJECT_VW>


@{
    ViewBag.Title = "Search Permits by Location";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered tableStyle" id="searchLocationTable">
    <thead>
        <tr>
            <th>
                Permit Number
            </th>
            <th>
                Address
            </th>
            <th>
                Permit Type
            </th>
            <th>
                Permit Type Desc.
            </th>
            <th>
                X Coord
            </th>
            <th>
                Y Coord
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.ActionLink(item.CASE_NUMBER, "Index", "PermitInfo", new { permitNum = item.CASE_NUMBER }, new AjaxOptions { HttpMethod = "Post" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LOCATION)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.CASE_TYPE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CASE_TYPE_DESC)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CX)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CY)
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<div class="col-sm-12">
    <button class="btn btn-raised btn-primary" onclick="history.go(-1);">Search Again</button>
</div>

@Scripts.Render("~/bundles/dataTables")
<script>
    $(document).ready(function () {
        $('#searchLocationTable').DataTable();
    });
</script>