Portal/Controllers/PermitInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Portal.Models.DB;
using Portal.Models.ViewModel;
using System.Web.Services;
using System.IO;

namespace Portal.Controllers
{
    public class PermitInfoController : Controller
    {
        private CityworksEntities db = new CityworksEntities();
       
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult GetPermitInfo(string permitNum)
        {
            var tab = (from c in db.CA_OBJECT_VW
                      where c.CASE_NUMBER.Contains(permitNum)
                      select c).ToList();
            return PartialView("_PermitInfo", tab);
        }

        public ActionResult GetPermitLocation(string permitNum)
        {
            var tab = (from a in db.CA_ADDRESS_VW
                       where a.CASE_NUMBER.Contains(permitNum)
                       select a).ToList();
            return PartialView("_PermitLocation", tab);
        }

        public ActionResult GetPermitPeople(string permitNum)
        {
            var tab = (from p in db.CA_PEOPLE_VW
                       where p.CASE_NUMBER.Contains(permitNum)
                       select p).ToList();
            return PartialView("_PermitPeople", tab);
        }

        public ActionResult GetPermitTasks(string permitNum)
        {
            var tab = (from t in db.CA_TASK_VW
                       where t.CASE_NUMBER.Contains(permitNum)
                       orderby t.TASK_ID
                       select t).ToList();
            return PartialView("_PermitTasks", tab);
        }

        public ActionResult GetPermitInspections(string permitNum)
        {
            var tab = (from i in db.CA_INSPECTION_REQ_VW
                       where i.CASE_NUMBER.Contains(permitNum)
                       select i).ToList();
            return PartialView("_PermitInspections", tab);
        }

        public ActionResult GetPermitFees(string permitNum)
        {
            var tab = (from f in db.CA_FEES_VW
                       where f.CASE_NUMBER.Contains(permitNum)
                       select f).ToList();
            return PartialView("_PermitFees", tab);
        }

        public ActionResult GetPermitPayments(string permitNum)
        {
            var tab = (from p in db.CA_PAYMENT_VW
                       where p.CASE_NUMBER.Contains(permitNum)
                       select p).ToList();
            return PartialView("_PermitPayments", tab);
        }

        
    }
}

Portal/Controllers/SearchByNumberController.cs
using Portal.Models.DB;
using System.Linq;
using System.Web.Mvc;

namespace Portal.Controllers
{
    public class SearchByNumberController : Controller
    {
        private CityworksEntities db = new CityworksEntities();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult PermitNumber()
        {
            return PartialView("_PermitNumberFormPartial");
            // return View();
        }

        [HttpPost]
        public PartialViewResult PermitNumber(string permitNumber)
        {
            var tab = from c in db.CA_OBJECT_VW
                      where c.CASE_NUMBER.Contains(permitNumber)
                      select c;
            return PartialView("_PermitNumberResultsPartial", tab);
        }
    }
}

Portal/Views/SearchByNumber/Index.cshtml
@{
    ViewBag.Title = "Search Permits by Number";
    ViewBag.Icon = @"<i class=""fa fa-search""></i>";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div id="search-form" >
    @Html.Action("PermitNumber", "SearchByNumber")
</div>
<div id="search-results"></div>

Portal/Views/SearchByNumber/_PermitNumberFormPartial.cshtml
@using (Html.BeginForm("PermitNumber", "SearchByNumber", FormMethod.Post, new { @class = "col-sm-12" }))
{

    <div class="row">
        @*<div class="col-sm-6">
                @Html.TextBox("permitNumber", null, new { @class = "form-control", @placeholder = "Enter permit number", required = "required" })
            </div>*@
        <div class="form-group label-floating">
            <div class="col-sm-6">
                <label for="permitNumber" class="control-label">Enter Username</label>
                @Html.TextBox("permitNumber", null, new { @class = "form-control", required = "required", @id = "permitNumber" })
            </div>
        </div>
    </div>
        <div class="row">
            <div class="col-sm-6">
                <button type="submit" class="btn btn-raised btn-primary">Search</button>
            </div>
        </div>
}

Portal/Views/SearchByNumber/_PermitNumberResultsPartial.cshtml
@model IEnumerable<Portal.Models.DB.CA_OBJECT_VW>

@{
    ViewBag.Title = "Search Permits by Number";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<body>
    <table class="table table-bordered tableStyle" id="searchNumberTable">
        <thead>
            <tr>
                <th>
                    Case Number
                </th>
                <th>
                    Case Type
                </th>
                <th>
                    Case Status
                </th>
                <th>
                    Location
                </th>
                <th>
                    Date Issued
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.CASE_NUMBER, "Index", "PermitInfo", new { permitNum = item.CASE_NUMBER }, new AjaxOptions { HttpMethod = "Post" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CASE_TYPE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CASE_STATUS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LOCATION)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DATE_ISSUED)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <div class="col-sm-12">
        <button class="btn btn-raised btn-primary" onclick="history.go(-1);">Search Again</button>
    </div>
</body>
</html>
 @Scripts.Render("~/bundles/dataTables")
<script>
    $(document).ready(function () {
        $('#searchNumberTable').DataTable();
    });
</script>