Portal/Models/ViewModel/ModifyAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Portal.Models.ViewModel
{
    public class ModifyAccount
    {
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }
        
        [DataType(DataType.Password)]
        [Compare("NewPassword", ErrorMessage = "Passwords do not match")]
        public string ConfirmPassword { get; set; }
    }
}

Portal/Controllers/ModifyAccountController.cs
using Portal.Models.DB;
using Portal.Models.EntityManager;
using Portal.Models.ViewModel;
using System;
using System.Data.Entity.Validation;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace Portal.Controllers
{
    public class ModifyAccountController : Controller
    {
        private CityworksEntities db = new CityworksEntities();

        
        public ActionResult Index()
        {
            UserViewModel model = new UserViewModel();
            var claimsIdentity = User.Identity as ClaimsIdentity;
            int userId = Convert.ToInt32(claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value);
            USER user = (from u in db.USERS
                         where u.USER_ID == userId
                         select u).FirstOrDefault();
            model.User = user;
            CONTRACTOR_VW contractor = (from c in db.CONTRACTOR_VW
                                        where c.USER_ID == userId
                                        select c).FirstOrDefault();
            model.Contractor = contractor;
            return View(model);
        }

        [HttpPost]
        public ActionResult SaveModifications(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                USER user = (from u in db.USERS
                             where u.LOGIN_ID == model.User.LOGIN_ID
                             select u).FirstOrDefault();
                UserManager UM = new UserManager();
               

                if (model.ModifyAccount.NewPassword != null)
                {
                    string currentPassword = UM.GetMD5Hash(model.ModifyAccount.Password);
                    if (user.PASSWORD != currentPassword)
                    {
                        ModelState.AddModelError("ModifyAccount.Password", "Current password is incorrect.");
                        return View("Index", model);
                    }

                    string newPassword = UM.GetMD5Hash(model.ModifyAccount.NewPassword);
                    user.PASSWORD = newPassword;
                }

                user.EMAIL_ID = model.User.EMAIL_ID;
                user.FIRST_NAME = model.User.FIRST_NAME;
                user.LAST_NAME = model.User.LAST_NAME;
                user.ADDRESS_LINE1 = model.User.ADDRESS_LINE1;
                user.ADDRESS_LINE2 = model.User.ADDRESS_LINE2;
                user.CITY_NAME = model.User.CITY_NAME;
                user.STATE_CODE = model.User.STATE_CODE;
                user.ZIP_CODE = model.User.ZIP_CODE;
                user.COUNTRY_CODE = model.User.COUNTRY_CODE;
                user.PHONE_HOME = model.User.PHONE_HOME;
                user.PHONE_MOBILE = model.User.PHONE_MOBILE;
                
                //CONTRACTOR contractor = (from c in db.CONTRACTORs
                //                         where c.BUSINESS_NAME == model.Contractor.BUSINESS_NAME
                //                         select c).FirstOrDefault();
                //contractor.BUSINESS_NAME = model.Contractor.BUSINESS_NAME;
                //contractor.ADDRESS_LINE1 = model.Contractor.ADDRESS_LINE1;
                //contractor.CITY_NAME = model.Contractor.CITY_NAME;
                //contractor.STATE_CODE = model.Contractor.STATE_CODE;
                //contractor.ZIP_CODE = model.Contractor.ZIP_CODE;
                //contractor.PHONE_WORK = model.Contractor.PHONE_WORK;
                //contractor.PHONE_MOBILE = model.Contractor.PHONE_MOBILE;

                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var entityValidationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in entityValidationErrors.ValidationErrors)
                        {
                            Response.Write("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                        }
                    }
                }
                return View("Index", model);
            }
            return View(model);
        }
    }
}

Portal/Views/ModifyAccount/Index.cshtml
@{
    ViewBag.Title = "Modify Account";
    ViewBag.Icon = @"<i class=""material-icons md-48"">mode_edit</i>";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Portal.Models.ViewModel.UserViewModel
@using (Html.BeginForm("SaveModifications", "ModifyAccount", FormMethod.Post))

{

    <h4 class="primary-text">Login Information</h4>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group label-floating">
                    <label class="control-label" for="User.LOGIN_ID">Login ID</label>
                    @*<input type="text" class="form-control" placeholder="Login Name" name="username" id="username" disabled="" value="@Html.DisplayFor(item => item.User.LOGIN_ID)" />*@
                    @Html.EditorFor(model => model.User.LOGIN_ID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group label-floating">
                    <label class="control-label" for="User.EMAIL_ID">Email</label>
                    @Html.EditorFor(model => model.User.EMAIL_ID, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
    </div>
    <br />
    <br />

    <h4 class="primary-text">Change Password</h4>

    <div class="form-group ">
        <div class="row">
            <div class="col-xs-4">
                <div class="form-group label-floating">
                    <label class="control-label" for="ModifyAccount.Password">Current Password</label>
                    @Html.PasswordFor(m => m.ModifyAccount.Password, new { id = "Password", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ModifyAccount.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group label-floating">
                    <label class="control-label" for="ModifyAccount.NewPassword">New Password</label>
                    @Html.PasswordFor(m => m.ModifyAccount.NewPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ModifyAccount.NewPassword)
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group label-floating">
                    <label class="control-label" for="ModifyAccount.ConfirmPassword">Confim Password</label>
                    @Html.PasswordFor(m => m.ModifyAccount.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ModifyAccount.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <br />
    <br />

    <h4 class="primary-text">Contact Information</h4>

    <div class="form-group ">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group label-floating">
                    <label class="control-label" for="User.FIRST_NAME">First Name</label>
                    @Html.EditorFor(model => model.User.FIRST_NAME, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group label-floating">
                    <label class="control-label" for="User.LAST_NAME">Last Name</label>
                    @Html.EditorFor(model => model.User.LAST_NAME, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="form-group label-floating">
            <label class="control-label" for="User.ADDRESS_LINE1">Address</label>
            @Html.EditorFor(model => model.User.ADDRESS_LINE1, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group label-floating">
        <label class="control-label" for="User.ADDRESS_LINE2">Address 2</label>
        @Html.EditorFor(model => model.User.ADDRESS_LINE2, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-4">
                <div class="form-group label-floating">
                    <label class="control-label" for="User.CITY_NAME">City</label>
                    @Html.EditorFor(model => model.User.CITY_NAME, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group label-floating">
                    <label class="control-label" for="User.STATE_CODE">State</label>
                    @Html.EditorFor(model => model.User.STATE_CODE, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="col-xs-4">
                <div class="form-group label-floating">
                    <label class="control-label" for="User.ZIP_CODE">Zip Code</label>
                    @Html.EditorFor(model => model.User.ZIP_CODE, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
    </div>

    <div class="form-group label-floating">
        <div class="row">
            <div class="col-xs-6">
                <label class="control-label" for="User.COUNTRY_CODE">Country</label>
                @Html.EditorFor(model => model.User.COUNTRY_CODE, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group label-floating">
                    <label class="control-label" for="User.PHONE_HOME">Home Phone</label>
                    @Html.EditorFor(model => model.User.PHONE_HOME, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group label-floating">
                    <label class="control-label" for="User.PHONE_MOBILE">Mobile Phone</label>
                    @Html.EditorFor(model => model.User.PHONE_MOBILE, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
    </div>

    @*<br />
        <h4>Contractor Information</h4>

        <div class="form-group label-floating">
            <div class="row">
                <div class="col-xs-12">
                    <label class="control-label" for="Contractor.BUSINESS_NAME">Business Name</label>
                    @Html.EditorFor(model => model.Contractor.BUSINESS_NAME, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-6">
                    <label class="control-label" for="contractorAddress">Contractor Address</label>
                    @Html.EditorFor(model => model.Contractor.ADDRESS_LINE1, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address 1" } })
                </div>
                <div class="col-xs-6">
                    <label class="control-label" for="contractorAddressSub">Contractor Address 2</label>
                    @Html.EditorFor(model => model.Contractor.ADDRESS_LINE2, new { htmlAttributes = new { @class = "form-control" }, @placeholder = "Address 2" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-4">
                    <label class="control-label" for="contractorCity">Contractor City</label>
                    @Html.EditorFor(model => model.Contractor.CITY_NAME, new { htmlAttributes = new { @class = "form-control", @placeholder = "City" } })
                </div>
                <div class="col-xs-4">
                    <label class="control-label" for="contractorState">Contractor State</label>
                    @Html.EditorFor(model => model.Contractor.STATE_CODE, new { htmlAttributes = new { @class = "form-control", @placeholder = "State" } })
                </div>
                <div class="col-xs-4">
                    <label class="control-label" for="contractorZip">Contractor Zip</label>
                    @Html.EditorFor(model => model.Contractor.ZIP_CODE, new { htmlAttributes = new { @class = "form-control", @placeholder = "Zip" } })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-4">
                    <label class="control-label" for="contractorPhone">Work Phone</label>
                    @Html.EditorFor(model => model.Contractor.PHONE_WORK, new { htmlAttributes = new { @class = "form-control", @placeholder = "Work Phone" } })
                </div>
                <div class="col-xs-4">
                    <label class="control-label" for="contractorEmail">Mobile Email</label>
                    @Html.EditorFor(model => model.Contractor.PHONE_MOBILE, new { htmlAttributes = new { @class = "form-control", @placeholder = "Mobile Phone" } })
                </div>
            </div>
        </div>*@
    <br />
    <br />
    <div id="regBtnGroup">
        <button class="btn btn-raised btn-primary" id="mdfyCancel" onclick="history.go(-1)">Cancel</button>
        <button type="submit" class="btn btn-raised btn-primary" id="mdfySubmit">Submit</button>
    </div>
}