Portal/Controllers/PermitInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Portal.Models.DB;
using Portal.Models.ViewModel;
using System.Web.Services;
using System.IO;

namespace Portal.Controllers
{
    public class PermitInfoController : Controller
    {
        private CityworksEntities db = new CityworksEntities();
       
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult GetPermitInfo(string permitNum)
        {
            var tab = (from c in db.CA_OBJECT_VW
                      where c.CASE_NUMBER.Contains(permitNum)
                      select c).ToList();
            return PartialView("_PermitInfo", tab);
        }

        public ActionResult GetPermitLocation(string permitNum)
        {
            var tab = (from a in db.CA_ADDRESS_VW
                       where a.CASE_NUMBER.Contains(permitNum)
                       select a).ToList();
            return PartialView("_PermitLocation", tab);
        }

        public ActionResult GetPermitPeople(string permitNum)
        {
            var tab = (from p in db.CA_PEOPLE_VW
                       where p.CASE_NUMBER.Contains(permitNum)
                       select p).ToList();
            return PartialView("_PermitPeople", tab);
        }

        public ActionResult GetPermitTasks(string permitNum)
        {
            var tab = (from t in db.CA_TASK_VW
                       where t.CASE_NUMBER.Contains(permitNum)
                       orderby t.TASK_ID
                       select t).ToList();
            return PartialView("_PermitTasks", tab);
        }

        public ActionResult GetPermitInspections(string permitNum)
        {
            var tab = (from i in db.CA_INSPECTION_REQ_VW
                       where i.CASE_NUMBER.Contains(permitNum)
                       select i).ToList();
            return PartialView("_PermitInspections", tab);
        }

        public ActionResult GetPermitFees(string permitNum)
        {
            var tab = (from f in db.CA_FEES_VW
                       where f.CASE_NUMBER.Contains(permitNum)
                       select f).ToList();
            return PartialView("_PermitFees", tab);
        }

        public ActionResult GetPermitPayments(string permitNum)
        {
            var tab = (from p in db.CA_PAYMENT_VW
                       where p.CASE_NUMBER.Contains(permitNum)
                       select p).ToList();
            return PartialView("_PermitPayments", tab);
        }

        
    }
}

Portal/Controllers/SearchByTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Portal.Models.DB;
using Portal.Models.ViewModel;
using System.Web.Services;
namespace Portal.Controllers
{
    public class SearchByTypeController : Controller
    {
        private CityworksEntities db = new CityworksEntities();
        // GET: SearchByName
        public ActionResult Index()
        {
            CaseTypes model = new CaseTypes();
            model.CaseTypeList = GetCaseTypes();
            Session["type"] = model;
            return View(model);
        }

        //[HttpGet]
        //public ActionResult SearchType()
        //{
        //    //CaseTypes model = new CaseTypes();
        //    //model.CaseTypeList = GetCaseTypes();
        //    //Session["type"] = model;
        //    //return PartialView("_SearchType",  model);
        //}


        public IEnumerable<SelectListItem> GetCaseTypes()
        {
            CaseTypes model = (CaseTypes)Session["type"];
            var data = from c in db.CASE_TYPE
                       orderby c.CASE_TYPE1
                       select new { c.CASE_TYPE1, c.CASE_TYPE_DESC, c.CASE_TYPE_ID };
            // List<string> groups = new List<string>();
            List<SelectListItem> groups = new List<SelectListItem>();

            groups.Add(new SelectListItem() { Text = "Select Case Type", Value = "Selected Case Type", Disabled = true, Selected = true });

            foreach (var rec in data)
            {
                groups.Add(new SelectListItem() { Text = rec.CASE_TYPE1 + ": " + rec.CASE_TYPE_DESC, Value = rec.CASE_TYPE1 });
            }

            IEnumerable<SelectListItem> test = groups;
            //Session["type"] = model;
            return test;
        }

        [HttpPost]
        public ActionResult SearchSubType(string caseType)
        {
            CaseTypes sessionModel = (CaseTypes)Session["type"];

            var data = (from b in db.BUS_CASE_VW
                        where b.CASE_TYPE == caseType
                        orderby b.SUB_TYPE
                        select new { b = b });
            List<SelectListItem> subTypeList = new List<SelectListItem>();

            if (data.Any(m => m.b.SUB_TYPE != null))
            {
                subTypeList.Add(new SelectListItem { Text = "Select Sub-Type", Value = "Selected Sub-Type", Disabled = true, Selected = true });

                foreach (var rec in data)
                {
                    subTypeList.Add(new SelectListItem() { Text = rec.b.SUB_TYPE + ": " + rec.b.SUB_TYPE_DESC, Value = rec.b.SUB_TYPE });
                }
            }
            sessionModel.SubTypeList = subTypeList;
            Session["type"] = sessionModel;
            return PartialView("CaseTypePartial", sessionModel);
        }

       

        [HttpPost]
        public ActionResult Search(string permitType, string subType, DateTime? fromDateInput, DateTime? toDateInput)
        {
            CaseTypes sessionModel = (CaseTypes)Session["type"];

            if (fromDateInput != null && toDateInput != null)
            {
                sessionModel.CaObject = (from p in db.CA_OBJECT_VW
                         where p.CASE_TYPE.Contains(permitType) && p.DATE_CREATED >= fromDateInput && p.DATE_CREATED <= toDateInput
                         select p).ToList();
            }

            else if (subType != "")
            {
                sessionModel.CaObject = (from p in db.CA_OBJECT_VW
                         where p.CASE_TYPE.Contains(permitType) && p.SUB_TYPE.Contains(subType)
                         select p).ToList();
            }
            else
            {
                sessionModel.CaObject = (from p in db.CA_OBJECT_VW
                         where p.CASE_TYPE.Contains(permitType)
                         select p).ToList();
            }

            Session["type"] = sessionModel;
            return PartialView("_SearchTypeResults", sessionModel);
        }
    }
}

Portal/Views/SearchByType/CaseTypePartial.cshtml
@model Portal.Models.ViewModel.CaseTypes


@if (Model.SubTypeList.Any())
{
    <div class="form-group label-floating">
        <div class="row">
            <div class="col-xs-6">
                <label class="control-label" for="SelectedSubType">Sub-Type</label>
                @Html.DropDownListFor(model => Model.SelectedSubType, Model.SubTypeList, new { @class = "form-control" })
            </div>
        </div>
    </div>
}

Portal/Views/SearchByType/Index.cshtml
@model Portal.Models.ViewModel.CaseTypes
@{
    ViewBag.Title = "Search Permits by Type";
    ViewBag.Icon = @"<i class=""fa fa-search""></i>";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="form-group">
    <div class="row">
        <div class="col-xs-6">
            <label class="control-label" for="SelectedCaseType">Case Type</label>
            @Html.DropDownListFor(model => Model.SelectedCaseType, Model.CaseTypeList, new { @class = "form-control" })
        </div>
    </div>
</div>

<div id="subTypes" class="hidden">
    @Html.Partial("CaseTypePartial", Model)
</div>

<div class="form-group hidden" id="dateWrapper">
    <div class="row">
        <div class="col-xs-3 date">
            <div class="input-group input-append date" id="fromDate">
                <input type="text" class="form-control" data-date-format="mm-dd-yyyy" id="fromDateInput" name="fromDateInput" placeholder="From Date" required="" />
                <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
            </div>
        </div>

        <div class="col-xs-3 date">
            <div class="input-group input-append date" id="toDate" name="toDate">
                <input type="text" class="form-control" data-date-format="mm-dd-yyyy" id="toDateInput" name="toDateInput" placeholder="To Date" required="" />
                <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <button type="button" class="btn btn-raised btn-primary" id="search">Search</button>
    </div>
</div>

<div id="load-modal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-header"></div>
                <div id="divLoading" class="text-center">
                    <i class="fa fa-cog fa-spin fa-3x fa-fw"></i>
                    <span class="sr-only">Loading...</span>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>
</div>

<div id="results" class="hidden">
    @Html.Partial("_SearchTypeResults", Model)
</div>
@Scripts.Render("~/bundles/dataTables")
<script>

        @*$(document).on('change', '#permitGroup', function () {
            $('#permitType').empty();
            var permitGroup = $('#permitGroup').val();
            var jsonData = JSON.stringify({ permitGroup: permitGroup });
            $.ajax({

                url: "@Url.Action("SearchType", "SearchByType")",
                type: 'POST',
                data: jsonData,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    $('#permitType').append(data);
                },
                error: function (response) {
                    alert(response.error());
                }
            });
        });*@

        $('#SelectedCaseType').change(function (event) {
            $('#load-modal').modal('show'); // start load
            $('#SelectedSubType').empty();
            var caseType = $('#SelectedCaseType').val();
            // caseType = caseType.substr(0, caseType.indexOf(':'));
            $.ajax({
                url: "@Url.Action("SearchSubType", "SearchByType")",
                type: 'POST',
                datatype: 'json',
                data: { caseType: caseType },
                success: function (data) {
                    $('#subTypes').show();
                    $('#subTypes').html(data);
                    $('#subTypes').removeClass('hidden');
                    $('#load-modal').modal('hide');
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $('#load-modal').modal('hide'); // end load
                    alert(errorThrown);
                }
            });
        })

        $('#fromDate, #toDate').datepicker({
            todayHighlight: true,
            todayBtn: true
        });

        $('#fromDate, #toDate').on("changeDate", function () {
            $('#fromDateInput').val(
                $('#fromDate').datepicker('getFormattedDate')
            );
            $('#toDateInput').val(
                $('#toDate').datepicker('getFormattedDate')
            );
        });

        $('#search').click(function (event) {
            $('#load-modal').modal('show');
            var subType = $('#SelectedSubType').val();
            var caseType = $('#SelectedCaseType').val();
            if (typeof(subType) == 'undefined') {
                subType = null;
            };
            
            var fromDate = $('#fromDateInput').val();
            var toDate = $('#toDateInput').val();

            $.ajax({
                url: "@Url.Action("Search", "SearchByType")",
                type: 'POST',
                datatype: 'json',
                data: { permitType: caseType, subType: subType, fromDateInput: fromDate, toDateInput: toDate },
                success: function (data) {
                    $('#results').show();
                    $('#results').html(data);
                    $('#results').removeClass('hidden');
                    $('#searchTypeTable').DataTable();
                    $('#searchTypeTable').removeClass('hidden');
                    $('#load-modal').modal('hide');
                },
            error: function (jqXHR, textStatus, errorThrown) {
                $('#load-modal').modal('hide'); // end load
                alert(errorThrown);
            }
        });
        })
</script>

Portal/Views/SearchByType/_SearchType.cshtml
@model Portal.Models.ViewModel.CaseTypes
@Styles.Render("~/Content/BootstrapDatePicker/css/bootstrap-datepicker.min.css")
@Styles.Render("~/Content/BootstrapDatePicker/css/bootstrap-datepicker3.min.css")
@Scripts.Render("~/Content/BootstrapDatePicker/js/bootstrap-datepicker.min.js")

<div class="form-group">
    <div class="row">
        <div class="col-xs-6">
            <label class="control-label" for="SelectedCaseType">Case Type</label>
            @Html.DropDownListFor(model => Model.SelectedCaseType, Model.CaseTypeList, new { @class = "form-control" })
        </div>
    </div>
</div>

<div id="subTypes" class="hidden">
    @Html.Partial("CaseTypePartial", Model)
</div>

<div class="form-group hidden" id="dateWrapper">
    <div class="row">
        <div class="col-xs-3 date">
            <div class="input-group input-append date" id="fromDate">
                <input type="text" class="form-control" data-date-format="mm-dd-yyyy" id="fromDateInput" name="fromDateInput" placeholder="From Date" required="" />
                <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
            </div>
        </div>

        <div class="col-xs-3 date">
            <div class="input-group input-append date" id="toDate" name="toDate">
                <input type="text" class="form-control" data-date-format="mm-dd-yyyy" id="toDateInput" name="toDateInput" placeholder="To Date" required="" />
                <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <button type="button" class="btn btn-raised btn-primary" id="search">Search</button>
    </div>
</div>


<div id="results" class="hidden">
    @Html.Partial("SearchTypeResults", Model)
</div>

<script>

    $('#SelectedCaseType').change(function (event) {
        $('#load-modal').modal('show'); // start load
        $('#SelectedSubType').empty();
        var caseType = $('#SelectedCaseType').val();
        // caseType = caseType.substr(0, caseType.indexOf(':'));
        $.ajax({
            url: "@Url.Action("SearchSubType", "SearchByType")",
            type: 'POST',
            datatype: 'json',
            data: { caseType: caseType },
            success: function (data) {
                $('#subTypes').show();
                $('#subTypes').html(data);
                $('#subTypes').removeClass('hidden');
                $('#load-modal').modal('hide');
            },
            error: function (jqXHR, textStatus, errorThrown) {
                $('#load-modal').modal('hide'); // end load
                alert(errorThrown);
            }
        });
    })

    $('#fromDate, #toDate').datepicker({
        todayHighlight: true,
        todayBtn: true
    });

    $('#fromDate, #toDate').on("changeDate", function () {
        $('#fromDateInput').val(
            $('#fromDate').datepicker('getFormattedDate')
        );
        $('#toDateInput').val(
            $('#toDate').datepicker('getFormattedDate')
        );
    });

    $('#search').click(function (event) {
        $('#load-modal').modal('show');
        $.ajax({
            url: "@Url.Action("Search", "SearchByType")",
            type: 'POST',
            datatype: 'json',
            data: { caseType: caseType },
            success: function (data) {
                $('#results').show();
                $('#results').html(data);
                $('#results').removeClass('hidden');
                $('#load-modal').modal('hide');
            },
            error: function (jqXHR, textStatus, errorThrown) {
                $('#load-modal').modal('hide'); // end load
                alert(errorThrown);
            }
        });
    })
</script>

Portal/Views/SearchByType/_SearchTypeResults.cshtml
@model Portal.Models.ViewModel.CaseTypes



<table class="table table-bordered tableStyle hidden table-responsive" id="searchTypeTable">
    <thead>
        <tr>
            <th>
                Permit Number
            </th>
            <th>
                Permit Type
            </th>
            <th>
                Permit Status
            </th>
            <th>
                Location
            </th>
            <th>
                Date Issued
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.CaObject )
            {

            <tr>
                <td>
                    @Html.ActionLink(item.CASE_NUMBER, "Index", "PermitInfo", new { permitNum = item.CASE_NUMBER }, new AjaxOptions { HttpMethod = "Post" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CASE_TYPE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CASE_STATUS)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LOCATION)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DATE_ISSUED)
                </td>
            </tr>
        }
    </tbody>
</table>
<br />